import { ClientTransfer } from "interfaces/ClientTransfer";
import React from "react";
import { Route, Routes } from "react-router-dom";
import TransfersList from "components/TransfersList/TransfersList.component";

type AppRoutesProps = {
  transfers: ClientTransfer[];
  filterQuery: string;
};

const AppRoutes = ({ transfers, filterQuery }: AppRoutesProps): JSX.Element => {
  return (
    <>
      <Routes>
        <Route
          path="/2023"
          element={
            <TransfersList
              transfers={transfers}
              season="2023"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2022"
          element={
            <TransfersList
              transfers={transfers}
              season="2022"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2021"
          element={
            <TransfersList
              transfers={transfers}
              season="2021"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2020"
          element={
            <TransfersList
              transfers={transfers}
              season="2020"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2019"
          element={
            <TransfersList
              transfers={transfers}
              season="2019"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2018"
          element={
            <TransfersList
              transfers={transfers}
              season="2018"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2017"
          element={
            <TransfersList
              transfers={transfers}
              season="2017"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2016"
          element={
            <TransfersList
              transfers={transfers}
              season="2016"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2015"
          element={
            <TransfersList
              transfers={transfers}
              season="2015"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2014"
          element={
            <TransfersList
              transfers={transfers}
              season="2014"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2013"
          element={
            <TransfersList
              transfers={transfers}
              season="2013"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2012"
          element={
            <TransfersList
              transfers={transfers}
              season="2012"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2011"
          element={
            <TransfersList
              transfers={transfers}
              season="2011"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2010"
          element={
            <TransfersList
              transfers={transfers}
              season="2010"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2009"
          element={
            <TransfersList
              transfers={transfers}
              season="2009"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2008"
          element={
            <TransfersList
              transfers={transfers}
              season="2008"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/2007"
          element={
            <TransfersList
              transfers={transfers}
              season="2007"
              filterQuery={filterQuery}
            />
          }
        />
        <Route
          path="/"
          element={
            <TransfersList
              transfers={transfers}
              season="Todos"
              filterQuery={filterQuery}
            />
          }
        />
      </Routes>
    </>
  );
};

export default AppRoutes;
